//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Batch_GR_TR
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sap_batch_gr
    {
        public string MatNo { get; set; }
        public string CustID { get; set; }
        public string FacNo { get; set; }
        public string Plant { get; set; }
        public string SLoc { get; set; }
        public int MvmntType { get; set; }
        public string PostDate { get; set; }
        public string PostTime { get; set; }
        public Nullable<int> QRQty { get; set; }
        public string HeaderText { get; set; }
        public int Action { get; set; }
    }
}
